@hostname =  http://localhost
@port = 8080
@host = {{hostname}}:{{port}}

@publisher = testapp001
@context = testcontext001

###
GET {{host}}

###

POST {{host}}/publisher HTTP/1.1
content-type: application/json

{ 
    "publisher" : "{{publisher}}", 
    "origin" : "app.test.com" , 
    "description" : "Test App"
}

###

GET {{host}}/{{publisher}} HTTP/1.1

###

POST {{host}}/{{publisher}}/context HTTP/1.1
content-type: application/json

{
    "context": "{{context}}",
    "origin": "app.test.com/{{context}}",
    "description": "Test Context",
    "kind": {
        "logs": ["message", "mode"]
    }
}

###


GET {{host}}/{{publisher}}/{{context}} HTTP/1.1

###

POST {{host}}/{{publisher}}/{{context}}/logs HTTP/1.1
content-type: application/json

{
    "logLevel" : "INFO",
    "message" : "Testing Logsmith",
    "mode" : "RESTClient"
}

###
POST {{host}}/{{publisher}}/{{context}}/logs HTTP/1.1
content-type: application/json

{
    "timestamp" : {{$timestamp}},
    "logLevel" : "WARN",
    "message" : "Testing Logsmith",
    "mode" : "RESTClient"
}

###
GET {{host}}/{{publisher}}/{{context}}/logs HTTP/1.1
content-type: application/json