version: '3.4'

services:
  monitor:
    image: ghcr.io/tanmoysg/logsmith-monitor:latest
    ports:
      - 8080:8080
    volumes:
      - monitorvolume:/usr/src/app/logfiles

volumes:
  monitorvolume:
