# This is a basic workflow to help you get started with Actions

name: Auto Testing Deployment

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 */1 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Check Values
        run: |
          curl --request GET --url ${{secrets.DEPLOYMENT_URI}} --header 'content-type: application/json' | jq .count
