# GitHub Workflow File to Create Release on GitHub when a git-tag is pushed to main

name: Release on Tagging

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Release
        uses: softprops/action-gh-release@v1